env:
  browser: true
  es6: true

ignorePatterns:
  - '**/api-worker/*.js'

extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - vue
rules: {
  no-debugger: off,
  vue/no-useless-template-attributes: off,
  vue/multi-word-component-names: off
}
